import {assetUrl} from "./assets.js";
export const UI_ICON_MAP={
 "coins": "coin",
 "star": "gold-star",
 "star-wallet": "star",
 "plus": "plus",
 "users": "friends",
 "gear": "settings",
 "xmark": "close",
 "pen": "edit",
 "circle-question": "help",
 "circle-info": "info",
 "check": "check",
 "lock": "lock",
 "clock": "clock",
 "calendar": "daily",
 "house": "home",
 "map": "map",
 "paw": "pets",
 "wand-magic-sparkles": "shop",
 "bullseye": "missions",
 "trophy": "trophy",
 "user": "profile",
 "skull": "boss",
 "flag-checkered": "flag",
 "gamepad": "gamepad",
 "hand-pointer": "touch",
 "volume-high": "volume",
 "music": "music",
 "shoe-prints": "speed",
 "palette": "palette",
 "bolt": "power",
 "sword": "sword",
 "moon": "magic",
 "shield-halved": "stamina",
 "sun": "sun",
 "snowflake": "frost",
 "wind": "wind",
 "chevron-left": "left",
 "chevron-right": "right",
 "crouch": "crouch",
 "arrow-down": "crouch"
};
export function croppedIcon(name){const crop=UI_ICON_MAP[name]||name;const url=assetUrl("ui/icons/"+crop);return url?`<img class="ico ui-icon" src="${url}" alt="" aria-hidden="true" draggable="false">`:null;}
