/* v1.3 interface extensions; existing gameplay and account actions remain authoritative. */
function forgeHeroCarousel(hero){return `<div class="forge-carousel"><button id="forgePrev" aria-label="Previous hero">‹</button><div id="forgeHeroCard"><img src="${ascOutfitUrl(hero.id)}" alt=""><div><b>${hero.name}</b><small>${save.ascension.outfits[hero.id]||'Starter'} · ${ASC_OUTFITS.length} outfits · ${COSMETIC_PARTS.length} accessory slots</small></div></div><button id="forgeNext" aria-label="Next hero">›</button></div>`;}
function bindForgeCarousel(hero){const move=d=>{ascForgeHero=HEROES[(HEROES.findIndex(h=>h.id===hero.id)+d+HEROES.length)%HEROES.length].id;renderForge();};$('forgePrev').onclick=()=>move(-1);$('forgeNext').onclick=()=>move(1);let start=null;const card=$('forgeHeroCard');card.onpointerdown=e=>{start=e.clientX;card.setPointerCapture(e.pointerId);};card.onpointerup=e=>{if(start!==null&&Math.abs(e.clientX-start)>35)move(e.clientX<start?1:-1);start=null;};card.onpointercancel=()=>start=null;}
let dashboardHero='all',dashboardIndex=0;
function renderRecords(){
 const local=['raid','pvp'].includes(ascRecordsMode), rows=(local?save.ascension.localRecords:save.ascension.records).filter(r=>r.mode===ascRecordsMode&&r.difficulty===ascRecordsDifficulty&&(ascRecordsMode==='endless'||r.world===ascRecordsWorld)&&(dashboardHero==='all'||r.hero===dashboardHero)&&(local?r.playerCount===localRecordPlayers&&(r.mode!=='pvp'||r.variant===localRecordVariant):(r.revision||1)===ASC_RULES_REVISION&&r.category===ascRecordsCategory)).slice().sort(local?(a,b)=>b.score-a.score:ascCompare);
 const select=(id,label,values,value)=>`<label>${label}<select id="${id}">${values.map(([v,n])=>`<option value="${v}" ${String(v)===String(value)?'selected':''}>${n}</option>`).join('')}</select></label>`;
 const r=rows[Math.min(dashboardIndex,rows.length-1)], details=r?Object.entries({'Best / clear time':formatTime(r.time),'Score':formatNumber(r.score),'Difficulty':r.difficulty,'Hero':heroById(r.hero).name,'Summon':PETS.find(p=>p.id===r.pet)?.name||r.loadout||'None','Hits received':r.hits??'Not recorded','Deaths':r.deaths??0,'Revives':r.revives??0,'Clear date':r.date,'Rules version':local?'Local normalized / raid':`Ascension ${r.revision||1}`,'Category':r.category||r.variant,'Players':r.playerCount||1}).map(([k,v])=>`<div><small>${k}</small><b>${escapeText(String(v))}</b></div>`).join(''): '<p>Complete a run with these filters to build your personal best.</p>';
 $('recordContent').innerHTML=`<div class="record-dashboard"><aside class="dashboard-filters">${select('rankMode','Mode',['campaign','boss','endless','daily','raid','pvp'].map(v=>[v,v]),ascRecordsMode)}${select('rankWorld','World / boss',WORLDS.map(w=>[w.id,w.name]),ascRecordsWorld)}${select('rankDiff','Difficulty',['veteran','nightmare','inferno'].map(v=>[v,v]),ascRecordsDifficulty)}${select('rankHero','Hero',[['all','All heroes'],...HEROES.map(h=>[h.id,h.name])],dashboardHero)}${local?select('rankPlayers','Player count',[2,3,4].map(v=>[v,v]),localRecordPlayers)+(ascRecordsMode==='pvp'?select('rankVariant','Rules',[['ffa','Free for all'],['teams','2v2']],localRecordVariant):''):select('rankCategory','Category',[['standard','Standard'],['open','Open builds']],ascRecordsCategory)}<p class="muted">Personal records on this device. Modes, difficulties, builds and player counts stay separate.</p></aside><section class="dashboard-list"><h3>${rows.length} recorded runs</h3>${rows.length?rows.map((v,i)=>`<button class="dashboard-row ${v===r?'selected':''}" data-record="${i}"><b>${i+1}</b><span>${heroById(v.hero).name}<small>${v.date} · ${v.grade||v.variant||'raid'}</small></span><strong>${formatTime(v.time)}<small>${formatNumber(v.score)} points</small></strong></button>`).join(''):'<div class="dashboard-empty">'+icon('trophy')+'<h3>No record yet</h3><p>No record yet — complete a run to place your first record.</p><button class="primary" id="firstRecord">Choose a world</button></div>'}</section><aside class="dashboard-detail"><h3>Run details / personal best</h3><div class="record-detail-grid">${details}</div><p class="muted">Solo clear rankings use adjusted time, then hits and score. Endless uses score. Earlier rules remain archived.</p></aside></div>`;
 const bind=(id,fn)=>{if($(id))$(id).onchange=e=>{fn(e.target.value);dashboardIndex=0;renderRecords();};};bind('rankMode',v=>ascRecordsMode=v);bind('rankWorld',v=>ascRecordsWorld=+v);bind('rankDiff',v=>ascRecordsDifficulty=v);bind('rankHero',v=>dashboardHero=v);bind('rankCategory',v=>ascRecordsCategory=v);bind('rankPlayers',v=>localRecordPlayers=+v);bind('rankVariant',v=>localRecordVariant=v);$('recordContent').querySelectorAll('[data-record]').forEach(b=>b.onclick=()=>{dashboardIndex=+b.dataset.record;renderRecords();});if($('firstRecord'))$('firstRecord').onclick=()=>showPage('campaign');
}
let profileTab='Overview';
function renderProfile(){
 renderProfileBase();const root=$('profileContent'),editor=root.querySelector('.profile-editor'),social=root.querySelector('.social-panel');
 const cleared=save.maps.filter(m=>m.clear).length,raids=save.ascension.localRecords.filter(r=>r.mode==='raid'),pvp=save.ascension.localRecords.filter(r=>r.mode==='pvp'),hero=heroById(save.hero),pet=PETS.find(p=>p.id===save.pet),level=1+Math.floor(save.xp/500),title=cleared?'World Explorer':'New Ascendant';
 const head=document.createElement('header');head.className='premium-profile-header';head.innerHTML=`${profileCard({...save.profile,...account.user})}<div><b>${title} · Level ${level}</b><progress max="500" value="${save.xp%500}"></progress><small>${save.xp%500} / 500 XP · ${save.profile.banner} banner · ${save.profile.frame} frame</small></div><div class="profile-showcase"><img src="${ascOutfitUrl(hero.id)}" alt="${hero.name}">${pet?`<img src="${assetUrl('pet/'+pet.id)}" alt="${pet.name}">`:''}<small>${hero.name} · ${pet?.name||'No summon equipped'}</small></div>`;
 const nav=document.createElement('nav');nav.className='profile-tabs';nav.innerHTML=['Overview','Achievements','Heroes','Cosmetics','Records','Social'].map(t=>`<button class="${t===profileTab?'selected':''}" data-profile-tab="${t}">${t}</button>`).join('');const body=document.createElement('section');body.className='profile-tab-body';
 root.replaceChildren(head,nav,body);
 const stats={'Campaign progress':`${starsTotal(save)} / 45 stars`,'Worlds completed':`${cleared} / 15`,'Bosses defeated':Object.keys(save.bossRecords).length,'Boss Hunt clears':save.ascension.records.filter(r=>r.mode==='boss').length,'Endless best':save.endless.best||0,'Raid clears':raids.filter(r=>r.clear).length,'PvP matches':pvp.length,'Favorite / equipped hero':hero.name,'Favorite / equipped summon':pet?.name||'None'};
 if(profileTab==='Overview')body.innerHTML=`<div class="premium-stats">${Object.entries(stats).map(([k,v])=>`<article><small>${k}</small><strong>${v}</strong></article>`).join('')}</div><p class="muted">Guilds — Coming later</p>`;
 if(profileTab==='Achievements')body.innerHTML=`<div class="premium-stats">${[['First Steps',cleared>0,'Complete a world'],['Sovereign Slayer',Object.keys(save.bossRecords).length>0,'Defeat a boss'],['Spirit Keeper',save.pets.length>0,'Rescue a summon'],['Journey Seeker',save.claims.length>0,'Claim a mission']].map(([n,done,desc])=>`<article><strong>${done?'✓':'○'} ${n}</strong><small>${desc}</small></article>`).join('')}</div>`;
 if(profileTab==='Heroes'){body.innerHTML=`<div class="profile-roster">${HEROES.map(h=>`<button data-profile-hero="${h.id}"><img src="${ascOutfitUrl(h.id)}" alt=""><b>${h.name}</b><small>Mastery Lv. ${Math.min(10,1+Math.floor((save.mastery[h.id]||0)/20))}</small></button>`).join('')}</div>`;body.querySelectorAll('[data-profile-hero]').forEach(b=>b.onclick=()=>{selectedHero=b.dataset.profileHero;showPage('heroes');});}
 if(profileTab==='Cosmetics'){body.appendChild(editor);const wardrobe=document.createElement('button');wardrobe.className='primary';wardrobe.textContent='Hero outfits & accessories';wardrobe.onclick=()=>showPage('forge');body.prepend(wardrobe);}
 if(profileTab==='Social')body.appendChild(social);
 if(profileTab==='Records'){body.innerHTML=`<div class="premium-stats">${Object.entries(stats).slice(0,7).map(([k,v])=>`<article><small>${k}</small><strong>${v}</strong></article>`).join('')}</div><button id="profileRecords" class="primary">Open competitive dashboard</button>`;$('profileRecords').onclick=()=>showPage('records');}
 nav.querySelectorAll('button').forEach(b=>b.onclick=()=>{profileTab=b.dataset.profileTab;renderProfile();});
}

function showPowerDiscovery(id){if(!run||run.mode==='local'||nearby?.state==='playing'||save.discoveredPowerUps.includes(id))return;const power=POWERS.find(p=>p.id===id);if(!power)return;save.discoveredPowerUps.push(id);persist();paused=true;clearInput();openModal('power-discovery',`${header(power.name,'POWER DISCOVERED',false)}<div class="power-discovery-icon">${icon(power.icon)}</div><p>${escapeText(power.description)}</p><p class="muted">This guide appears once per power-up. Reset gameplay tutorials in Settings to see it again.</p><button id="powerGotIt" class="primary">GOT IT</button>`);$('powerGotIt').onclick=()=>{closeModal();clearInput();paused=false;};}
