import test from'node:test';import assert from'node:assert/strict';import {createAccountServer}from'../server/index.mjs';import{normalizeOrigin}from'../game/social.js';
const password='A-testing-password-4821';
test('account service: real HTTP, SQLite, password hashing, friends and lifecycle',async t=>{
 const{server,db}=createAccountServer({dbPath:':memory:',rateLimit:false,origins:['https://appassets.androidplatform.net']});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));const base='http://127.0.0.1:'+server.address().port;
 const call=async(path,method='GET',data,token,origin)=>{const r=await fetch(base+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...(origin?{Origin:origin}:{})},body:data?JSON.stringify(data):undefined});return{status:r.status,data:(r.headers.get('Content-Type')||'').includes('json')?await r.json():await r.text(),headers:r.headers};};
 let a,b;
 await t.test('health and explicit CORS allowlist',async()=>{assert.equal((await call('/health')).status,200);assert.equal((await call('/health','GET',null,null,'https://evil.example')).status,403);assert.equal((await call('/health','GET',null,null,'https://appassets.androidplatform.net')).headers.get('access-control-allow-origin'),'https://appassets.androidplatform.net');});
 await t.test('signup requires long password and rules acceptance',async()=>{assert.equal((await call('/api/signup','POST',{username:'alice',password:'tiny',acceptRules:true})).status,400);assert.equal((await call('/api/signup','POST',{username:'alice',password})).status,400);});
 await t.test('two real accounts and one-time recovery codes',async()=>{a=(await call('/api/signup','POST',{username:'alice',password,acceptRules:true,profile:{name:'Alice',avatar:'garsi'}})).data;b=(await call('/api/signup','POST',{username:'boris',password,acceptRules:true})).data;assert(a.token&&b.token);assert.equal(a.recoveryCode.length,40);assert.notEqual(a.user.code,b.user.code);});
 await t.test('database never stores plaintext password, bearer token or recovery code',()=>{const row=db.prepare('SELECT * FROM accounts WHERE username=?').get('alice');assert(!row.password.includes(password));assert(!row.recovery.includes(a.recoveryCode));assert(!db.prepare('SELECT hash FROM sessions').all().some(x=>x.hash===a.token));});
 await t.test('wrong-password response and duplicate username',async()=>{assert.equal((await call('/api/login','POST',{username:'alice',password:'incorrect-password'})).status,401);assert.equal((await call('/api/signup','POST',{username:'alice',password,acceptRules:true})).status,409);});
 await t.test('real login rotates opaque bearer session and returns no password hash',async()=>{const r=await call('/api/login','POST',{username:'alice',password});assert.equal(r.status,200);assert.notEqual(r.data.token,a.token);assert(!('password'in r.data.user));});
 await t.test('profile has safe built-in cosmetics and strips markup',async()=>{const r=await call('/api/profile','PATCH',{name:'<b>Alice</b>',avatar:'https://evil',banner:'void',frame:'astral'},a.token);assert.equal(r.status,200);assert(!r.data.user.name.includes('<'));assert.equal(r.data.user.avatar,'wissem');assert.equal(r.data.user.frame,'astral');});
 await t.test('friends only connect after recipient consent',async()=>{assert.equal((await call('/api/friends/request','POST',{code:b.user.code},a.token)).status,200);let r=await call('/api/friends','GET',null,b.token);assert.equal(r.data.incoming.length,1);assert.equal(r.data.friends.length,0);assert.equal((await call('/api/friends/respond','POST',{id:a.user.id,accept:true},b.token)).status,200);r=await call('/api/friends','GET',null,a.token);assert.equal(r.data.friends[0].id,b.user.id);});
 await t.test('a report is persisted for operator review, not fabricated moderation',async()=>{assert.equal((await call('/api/report','POST',{id:b.user.id,reason:'name'},a.token)).status,200);assert.equal(db.prepare('SELECT status FROM reports').get().status,'open');});
 await t.test('blocking removes friendship and forbids renewed requests',async()=>{assert.equal((await call('/api/block','POST',{id:b.user.id},a.token)).status,200);assert.equal((await call('/api/friends','GET',null,b.token)).data.friends.length,0);assert.equal((await call('/api/friends/request','POST',{code:a.user.code},b.token)).status,404);});
 await t.test('logout invalidates token immediately',async()=>{assert.equal((await call('/api/logout','POST',{},b.token)).status,200);assert.equal((await call('/api/me','GET',null,b.token)).status,401);});
 await t.test('recovery rotates recovery code and invalidates previous sessions',async()=>{const r=await call('/api/recover','POST',{username:'alice',password:'A-new-password-for-Alice',recoveryCode:a.recoveryCode});assert.equal(r.status,200);assert.notEqual(r.data.recoveryCode,a.recoveryCode);assert.equal((await call('/api/me','GET',null,a.token)).status,401);a=r.data;});
 await t.test('delete requires reauthentication, cascades records and anonymizes safety report',async()=>{assert.equal((await call('/api/account','DELETE',{password:'bad'},a.token)).status,401);assert.equal((await call('/api/account','DELETE',{password:'A-new-password-for-Alice'},a.token)).status,200);assert.equal((await call('/api/me','GET',null,a.token)).status,401);assert.equal(db.prepare('SELECT COUNT(*) AS n FROM accounts').get().n,1);assert.equal(db.prepare('SELECT reporter FROM reports').get().reporter,null);});
 await t.test('public deletion page exists with working endpoint form',async()=>{const r=await call('/delete-account');assert.equal(r.status,200);assert(r.data.includes('/api/account'));assert(r.headers.get('content-security-policy').includes("frame-ancestors 'none'"));});
 await t.test('untrusted JSON and oversized payload rejected',async()=>{assert.equal((await call('/api/signup','POST',['bad'])).status,400);const r=await call('/api/signup','POST',{username:'large',password:'x'.repeat(17000)});assert.equal(r.status,413);});
});
test('HTTPS origin validation rejects paths, credentials, queries and cleartext',()=>{assert.equal(normalizeOrigin('https://accounts.example.com'),'https://accounts.example.com');for(const x of ['http://a.example','https://a.example/api','https://u:p@a.example','https://a.example?token=1','javascript:alert(1)'])assert.throws(()=>normalizeOrigin(x));});
test('rate limiter returns 429 after bounded failed-login attempts',async t=>{const {server}=createAccountServer({dbPath:':memory:'});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));let status;for(let i=0;i<12;i++){const r=await fetch('http://127.0.0.1:'+server.address().port+'/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:'missing',password})});status=r.status;await r.text();}assert.equal(status,429);});

 test('account client sanitizes server-controlled profile markup and rejects injected identity fields',async()=>{const{accountResponse}=await import('../game/social.js');const user={id:'a'.repeat(24),username:'racer',code:'ABCDEF1234',name:'<img src=x>',banner:'evil\" onclick=1',frame:'bad',avatar:'../../bad'};const safe=accountResponse({user}).user;assert.equal(safe.banner,'aurora');assert.equal(safe.frame,'silver');assert.equal(safe.avatar,'wissem');assert.ok(!safe.name.includes('<'));assert.throws(()=>accountResponse({user:{...user,id:'\" onclick=1'}}));assert.throws(()=>accountResponse({token:'bad'}));});
