import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {HEROES,PETS,WORLDS,VERSION,DT} from '../game/data.js';
import {createRun,createBossTrial,stepRun,activateCompanion,activatePetSkill,activateSkill,damagePlayer,damageBoss,advanceEndless,makeEnemy} from '../game/engine.js';
import {defaultSave,sanitizeSave,recordRun,bankRunStats,saveProgress,loadSave} from '../game/progress.js';
import {ASC_FUSIONS,ascHeroSkills,ascBuyOutfit,ascLearn,ascEquipSkill,ascFuseSkill,ascFusePet,ascApplyRun,ascCompare,ascSanitize} from '../game/ascension.js';
import {CONTROL_IDS,defaultControlPreset,sanitizeControlPresets,controlRect} from '../game/controls.js';
import {NearbySession,validRoomCode,roomCode} from '../game/link.js';
import {LocalMatch,validSnapshot,snapshotView,LINK_PROTOCOL,cleanPeerProfile} from '../game/arena.js';
const ticks=(r,n,input={})=>{for(let i=0;i<n;i++)stepRun(r,input,DT);};
const safeRun=(pet=null)=>{const r=createRun(0,'wissem','practice',0,pet);r.level.enemies=[];r.player.soul=100;return r;};
const roster=n=>['host','slot1','slot2','slot3'].slice(0,n).map((id,i)=>({id,profile:{name:id,hero:HEROES[i].id,avatar:'wissem',pet:i===1?'wolf':null},ready:true}));
function wired(n=2,code='012345'){
 const q=[],sessions={};for(const id of roster(n).map(x=>x.id))sessions[id]=new NearbySession({profile:{name:id},send:(to,message)=>q.push({from:id,to,message})});
 const flush=()=>{for(let limit=0;q.length&&limit<10000;limit++){const {from,to,message}=q.shift();sessions[to].receive(from,JSON.stringify(message));}assert(q.length===0,'message loop bounded');};
 sessions.host.hostLobby(code);for(const id of Object.keys(sessions).slice(1)){sessions[id].prepareJoin(code);sessions.host.connected(id);sessions[id].connected('host');}flush();return{q,sessions,flush};
}

test('public version 1.4.1, ten heroes, seven pets plus two fusion results',()=>{assert.equal(VERSION,'1.4.1');assert.equal(HEROES.length,10);assert.equal(PETS.length,9);assert.equal(PETS.filter(p=>p.recipe).length,2);for(const h of HEROES){assert(h.backstory.length>80);assert.equal(h.skills.length,2);}assert.equal(new Set(HEROES.flatMap(h=>h.skills.map(s=>s.id))).size,20);});
test('fifteen extended worlds use supplied tiled environments, no fake extra map count',()=>{for(const w of WORLDS){assert.equal(w.length,w.baseLength*5);assert(['waste','starry'].includes(w.tileSet));assert.equal(w.regions.length,5);const r=createRun(w.id);assert.equal(r.level.chambers.length,3);assert.equal(r.level.eggs.filter(p=>['skywolf','emberguard'].includes(p.id)).length,0);}});
test('license attribution exists; unidentified icon directory not bundled',()=>{const m=JSON.parse(fs.readFileSync('assets/manifest.json'));assert(Object.keys(m.images).filter(x=>x.startsWith('skill-icon/')).length===54);assert(m.images['environment/starry-sky']);assert(m.images['environment/waste-sky']);assert.equal(m.images['environment/water'].frames,4);assert.equal(m.images['environment/spikes'].frames,6);assert(fs.readFileSync('licenses/COMMUNITY-ASSETS.md','utf8').includes('Batareya'));assert(!Object.values(m.images).some(x=>x.path.startsWith('Icons/')));});
for(const pet of PETS)test(`${pet.name}: inactive, resource cost, charge budget, true expiry`,()=>{
 const r=safeRun(pet.id);ticks(r,10);assert.equal(r.player.petTime,0);assert.equal(r.stats.kills,0);assert(activateCompanion(r));assert.equal(r.player.petTime,pet.summonDuration);assert.equal(r.player.soul,100-pet.summonCost);assert.equal(r.player.companionCharges,pet.summonCharges-1);assert(!activateCompanion(r));ticks(r,Math.ceil(pet.summonDuration/DT)+2);assert.equal(r.player.petTime,0);assert.equal(r.player.scales,0);assert.equal(r.player.breath,0);assert.equal(r.player.flood,0);assert.equal(r.player.prince,0);assert(!r.petState.guard);assert(r.player.companionCooldown>0);assert(!activateCompanion(r));
});
test('low soul, exhausted calls, PvP, death and cooldown deny summons without spending',()=>{for(const mutation of [r=>r.player.soul=0,r=>r.player.companionCharges=0,r=>r.localPvp=true,r=>r.player.deadFor=1,r=>r.player.companionCooldown=2]){const r=safeRun('wolf');mutation(r);const soul=r.player.soul,charges=r.player.companionCharges;assert(!activateCompanion(r));assert.equal(r.player.soul,soul);assert.equal(r.player.companionCharges,charges);}});
test('inactive wolf never attacks; active wolf deals damage and stops after expiry',()=>{const r=safeRun('wolf');const e=makeEnemy('golem',235,999);e.vx=0;r.level.enemies=[e];ticks(r,60);assert.equal(e.hp,3);assert(activateCompanion(r));ticks(r,5);assert(e.hp<3);r.player.petTime=0;const e2=makeEnemy('golem',235,998);e2.vx=0;r.level.enemies=[e2];r.player.x=120;r.petState.timer=0;ticks(r,60);assert.equal(e2.hp,3);});
test('turtle provides exactly one guard during each limited summon',()=>{const r=safeRun('turtle');r.player.invincible=0;damagePlayer(r);assert.equal(r.player.hp,3);r.player.invincible=0;assert(activateCompanion(r));damagePlayer(r);assert.equal(r.player.hp,3);assert(!r.petState.guard);r.player.invincible=0;damagePlayer(r);assert.equal(r.player.hp,2);});
test('dragon abilities require summon and cannot outlive its ten-second window',()=>{const r=safeRun('dragon');assert(!activatePetSkill(r));assert(activateCompanion(r));assert.equal(r.player.scales,15);ticks(r,120);assert(activatePetSkill(r));assert(r.player.breath<=8.01);ticks(r,485);assert.equal(r.player.breath,0);assert.equal(r.player.scales,0);assert.equal(r.player.companionCharges,0);});
test('Orca clears ordinary enemies but not bosses; water support expires with summon',()=>{const r=safeRun('orca');assert(activateCompanion(r));assert(activatePetSkill(r));const e=makeEnemy('slime',500,1);r.level.enemies=[e];ticks(r,1);assert(!e.alive);r.player.soul=30;assert(activatePetSkill(r,1));assert(r.player.prince<=12);const b=createBossTrial(0,'wissem','nightmare','orca');b.player.soul=100;assert(activateCompanion(b));const before=b.boss.hp;assert(activatePetSkill(b));assert.equal(b.boss.hp,before);ticks(r,725);assert.equal(r.player.prince,0);assert.equal(r.player.flood,0);});
test('endless world changes preserve summon lifetime, spent calls and cooldown',()=>{const r=createRun(14,'wissem','endless',14,'dragon');r.player.soul=100;activateCompanion(r);r.player.petTime=6;r.player.companionCooldown=175;advanceEndless(r);assert.equal(r.worldId,0);assert.equal(r.player.petTime,6);assert.equal(r.player.companionCharges,0);assert.equal(r.player.companionCooldown,175);});
test('wall contact enables slide then wall jump away from the wall',()=>{const r=safeRun();for(let y=4;y<12;y++)r.level.tiles[y][10]=1;Object.assign(r.player,{x:372,y:310,vx:150,vy:100,coyote:0,grounded:false});ticks(r,5,{axis:1});assert(r.player.wallTime>0);assert(r.player.vy<=91);stepRun(r,{jump:true,axis:1},DT);assert(r.player.vy<0);assert(r.player.vx<0);});
test('boss stagger creates a recovery window and does not stunlock',()=>{const r=createBossTrial();const b=r.boss;b.state='recover';b.invuln=0;for(let i=0;i<10;i++){b.invuln=0;damageBoss(r,b,2,'melee');}assert.equal(b.state,'stagger');assert(b.staggerLock>0);assert.equal(b.stagger,0);b.invuln=0;damageBoss(r,b,1,'melee');assert.equal(b.stagger,0);});

test('four independent presets and bounded geometry at phone and tablet sizes',()=>{const slots=sanitizeControlPresets();assert.equal(slots.length,4);slots[0].buttons.jumpControl.x=.1;assert.notEqual(slots[1].buttons.jumpControl.x,.1);for(const [w,h]of [[640,360],[844,390],[960,540],[1280,720]])for(const p of slots)for(const id of CONTROL_IDS){const b=controlRect(p.buttons[id],w,h);assert(b.size>=44);assert(b.x-b.size/2>=0);assert(b.y-b.size/2>=0);assert(b.x+b.size/2<=w);assert(b.y+b.size/2<=h);}});
test('control sanitizer rejects nonfinite values and clamps offscreen positions',()=>{const r=defaultControlPreset();r.buttons.jumpControl={x:Infinity,y:-100,size:999,opacity:-8};const p=sanitizeControlPresets([r])[0];assert(Number.isFinite(p.buttons.jumpControl.x));assert.equal(p.buttons.jumpControl.y,.045);assert.equal(p.buttons.jumpControl.size,152);assert.equal(p.buttons.jumpControl.opacity,.25);});
test('v4 save import keeps earned gold, heroes, pets and adds controls/loadouts',()=>{const old=defaultSave();delete old.ascension;delete old.controlPresets;old.version=4;old.gold=4500;old.pets=['wolf','dragon'];old.pet='dragon';old.hero='kossay';const s=sanitizeSave(old);assert.equal(s.version,5);assert.equal(s.gold,4500);assert.equal(s.pet,'dragon');assert.equal(s.hero,'kossay');assert.equal(s.controlPresets.length,4);assert.deepEqual(ascHeroSkills(s.ascension,'kossay').map(x=>x.id),['fang','snare']);});
test('four edited presets survive actual save serialization and reload',()=>{const s=defaultSave(),m=new Map();const storage={getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v)};for(let i=0;i<4;i++)s.controlPresets[i].buttons.jumpControl.x=.11+i*.15;s.controlActive=3;assert(saveProgress(storage,s));const loaded=loadSave(storage).save;assert.equal(loaded.controlActive,3);for(let i=0;i<4;i++)assert.equal(loaded.controlPresets[i].buttons.jumpControl.x,.11+i*.15);});
test('starter/frost are free; outfit purchase spends once and cannot overdraw',()=>{const s=defaultSave();assert(ascBuyOutfit(s,'wissem','frost'));assert.equal(s.gold,0);assert(!ascBuyOutfit(s,'wissem','ember'));s.gold=800;assert(ascBuyOutfit(s,'wissem','ember'));assert.equal(s.gold,0);assert(ascBuyOutfit(s,'wissem','ember'));assert.equal(s.gold,0);assert(!ascBuyOutfit(s,'injected','ember'));});
test('skill books have a fixed cost; equip prevents duplicate skills and unknown IDs',()=>{const s=defaultSave();assert(!ascLearn(s,'orbit'));s.gold=350;assert(ascLearn(s,'orbit'));assert.equal(s.gold,0);assert(!ascLearn(s,'orbit'));assert(ascEquipSkill(s,'wissem',0,'orbit'));assert(!ascEquipSkill(s,'wissem',1,'orbit'));assert(!ascEquipSkill(s,'wissem',0,'not-a-skill'));const r=createRun();ascApplyRun(s,r);assert.equal(r.player.skillId1,'orbit');assert.equal(r.loadoutCategory,'open');assert(activateSkill(r,0));assert(r.player.orbit>0);});
for(const f of ASC_FUSIONS)test(`${f.name}: deterministic unlock, fixed focus budget and cooldown`,()=>{const s=defaultSave();s.gold=f.cost;assert(ascFuseSkill(s,f.id));assert.equal(s.gold,0);assert(!ascFuseSkill(s,f.id));assert(ascEquipSkill(s,'wissem',0,f.id));const r=createRun();ascApplyRun(s,r);assert(activateSkill(r,0));assert.equal(r.player.focus,50);assert(!activateSkill(r,0));assert.equal(r.loadoutCategory,'open');});
test('pet fusion requires both rescued parents and keeps them intact',()=>{const s=defaultSave();s.gold=2000;s.pets=['wolf'];assert(!ascFusePet(s,'skywolf'));assert.equal(s.gold,2000);s.pets.push('eagle');assert(ascFusePet(s,'skywolf'));assert.equal(s.gold,800);assert(s.pets.includes('wolf')&&s.pets.includes('eagle'));assert(s.pets.includes('skywolf'));assert(!ascFusePet(s,'skywolf'));assert(sanitizeSave(s).pets.includes('skywolf'));});
test('ranking records are idempotent and split open vs standard; practice never ranks',()=>{const s=defaultSave(),r=createBossTrial();ascApplyRun(s,r);r.complete=true;r.bossTime=72;r.hits=1;recordRun(s,r);recordRun(s,r);assert.equal(s.ascension.records.length,1);assert.equal(s.ascension.records[0].category,'standard');assert.equal(s.ascension.records[0].grade,'S');const p=createRun(0,'wissem','practice');p.complete=true;recordRun(s,p);assert.equal(s.ascension.records.length,1);});
test('rank order is explicit: time then hits then score; endless highest score',()=>{const a={mode:'boss',time:80,hits:1,score:100},b={...a,time:90,score:10000};assert(ascCompare(a,b)<0);assert(ascCompare(a,{...a,hits:2})<0);assert(ascCompare(a,{...a,score:200})>0);assert(ascCompare({...a,mode:'endless',score:300},{...b,mode:'endless',score:200})<0);});
test('stored ranking markup and arbitrary assets are sanitized',()=>{const s=ascSanitize({records:[{rules:'ascension-1',mode:'boss',world:0,category:'standard',difficulty:'veteran',score:2,time:2,grade:'<img onerror=x>',hero:'https://evil',pet:'https://evil',date:'<b>today'}]});assert.equal(s.records[0].grade,'C');assert.equal(s.records[0].hero,'wissem');assert.equal(s.records[0].pet,null);assert.equal(s.records[0].date,'');});
test('camera experiment practice cannot award coins, skill mastery, or records',()=>{const s=defaultSave(),r=createRun(0,'wissem','practice');r.cameraExperiment=true;r.complete=true;r.coinsEarned=1000;r.stats.skills=30;r.stats.coins=1000;bankRunStats(s,r);recordRun(s,r);assert.equal(s.gold,0);assert.deepEqual(s.mastery,{});assert.equal(s.ascension.records.length,0);});

test('six-digit codes preserve leading zeros and reject malformed input',()=>{assert(validRoomCode('000042'));for(const x of ['12345','1234567','123 45','１２３４５６',null,123456])assert(!validRoomCode(x));for(let i=0;i<100;i++)assert(validRoomCode(roomCode()));});
test('wrong-code connection cannot receive roster, send ready, or start gameplay',()=>{const sent=[],host=new NearbySession({send:(to,m)=>sent.push({to,m})});host.hostLobby('000042');host.connected('slot1');assert(!host.receive('slot1',JSON.stringify({type:'hello',protocol:LINK_PROTOCOL,code:'999999',profile:{name:'Guest'}})));assert.equal(host.roster.length,1);host.broadcastLobby();assert(!sent.some(x=>x.m.type==='lobby'));assert(!host.receive('slot1',JSON.stringify({type:'ready',protocol:LINK_PROTOCOL,ready:true})));assert.throws(()=>host.start());});
test('three incorrect code attempts disconnect the unadmitted peer',()=>{const removed=[],h=new NearbySession({send:()=>{},onReject:id=>removed.push(id)});h.hostLobby('555555');h.connected('slot1');for(let i=0;i<3;i++)h.receive('slot1',JSON.stringify({type:'hello',protocol:LINK_PROTOCOL,code:'111111'}));assert.deepEqual(removed,['slot1']);assert(!h.connections.has('slot1'));assert.equal(h.roster.length,1);});
test('two clients admit by code, require ready, then receive real shared raid snapshots',()=>{const{sessions:s,flush}=wired();assert.equal(s.host.roster.length,2);assert.equal(s.slot1.roomCode,'012345');assert.throws(()=>s.host.start());s.slot1.ready(true);flush();s.host.start();flush();assert.equal(s.slot1.state,'playing');for(let i=0;i<210;i++){s.slot1.step({axis:.3},DT);flush();s.host.step({},DT);flush();}assert(s.slot1.snapshot);assert(validSnapshot(s.slot1.snapshot));assert.equal(s.slot1.snapshot.players[0].boss.hp,s.slot1.snapshot.players[1].boss.hp);});
for(const n of [2,3,4])test(`${n}-player shared raid: scaled boss, bounded snapshot, correct avatars and pets`,()=>{const m=new LocalMatch({mode:'raid',roster:roster(n)});const hp=m.players[0].run.boss.hp;assert(hp>75);for(const p of m.players)assert.equal(p.run.boss,m.sharedBoss);assert.equal(m.revivePool,n);const snap=m.snapshot();assert(validSnapshot(snap));assert(Buffer.byteLength(JSON.stringify(snap))<65536);const view=snapshotView(snap,'slot1');assert.equal(view.petId,'wolf');assert.equal(view.player.character,'kossay');assert(!view.localPvp);assert.equal(view.remotePlayers.length,n-1);});
test('shared raid AI advances once per tick, not once per player',()=>{const a=new LocalMatch({mode:'raid',roster:roster(2)}),b=new LocalMatch({mode:'raid',roster:roster(4)});a.countdown=b.countdown=0;for(let i=0;i<60;i++){a.step();b.step();}assert(Math.abs(a.sharedBoss.t-b.sharedBoss.t)<1e-9);assert(Math.abs(a.sharedBoss.t-1)<.001);});
test('hold-to-revive consumes one shared revive after three seconds',()=>{const m=new LocalMatch({mode:'raid',roster:roster(2)});m.countdown=0;m.time=3;const [a,b]=m.players;Object.assign(a.run.player,{x:180,y:436,invincible:1000});Object.assign(b.run.player,{x:230,y:436,hp:0});b.run.failed=true;for(let i=0;i<185;i++){m.input('host',{seq:i,input:{interact:true}});m.step();}assert(!b.run.failed);assert(b.run.player.hp>0);assert.equal(m.revivePool,1);assert.equal(a.revives,1);});
test('released revive input resets progress instead of reviving at a distance',()=>{const m=new LocalMatch({mode:'raid',roster:roster(2)});m.countdown=0;m.time=3;const [a,b]=m.players;Object.assign(a.run.player,{x:180,y:436,invincible:1000});Object.assign(b.run.player,{x:230,y:436,hp:0});b.run.failed=true;for(let i=0;i<65;i++){m.input('host',{seq:i,input:{interact:true}});m.step();}assert(b.revive>0);m.input('host',{seq:66,input:{}});m.step();assert.equal(b.revive,0);assert(b.run.failed);assert.equal(m.revivePool,2);});
test('team wipe and shared victory produce team results, never an invented player winner',()=>{const m=new LocalMatch({mode:'raid',roster:roster(2)});m.countdown=0;m.players.forEach(p=>p.run.failed=true);m.step();assert.equal(m.result.reason,'team-wipe');assert.equal(m.result.winner,null);const n=new LocalMatch({mode:'raid',roster:roster(2)});n.countdown=0;n.sharedBoss.defeated=true;n.step();assert.equal(n.result.winner,'TEAM');assert.equal(n.result.reason,'raid-clear');});
test('malformed snapshot members and null profiles are safely rejected/sanitized',()=>{assert.equal(cleanPeerProfile(null).name,'Explorer');const m=new LocalMatch({mode:'raid',roster:roster(2)});let s=m.snapshot();s.players[0]=null;assert.equal(validSnapshot(s),false);s=m.snapshot();s.players[0].petState={x:Infinity,y:0};assert.equal(validSnapshot(s),false);});
test('native protocol, room clipboard and 64KiB framing are in the compiled-host sources',()=>{const bridge=fs.readFileSync('app/src/main/java/com/superwiss/game/playtest/NativeBridge.java','utf8');assert(bridge.includes('protocol\\\":5'));assert(bridge.includes('setPrimaryClip'));const link=fs.readFileSync('app/src/main/java/com/superwiss/game/playtest/BluetoothLink.java','utf8');assert(link.includes('n>65536'));assert(link.includes('while(g==generation)'));});

test('remote result UI rejects nonnumeric revive and damage fields',()=>{const m=new LocalMatch({mode:'raid',roster:roster(2)});m.finish('raid-clear');const s=m.snapshot();assert(validSnapshot(s));s.result.rows[0].revives='<img src=x onerror=alert(1)>';assert(!validSnapshot(s));});
