import test from'node:test';import assert from'node:assert/strict';
import {LocalMatch,cleanInput,snapshotView,LINK_PROTOCOL}from'../game/arena.js';import{NearbySession}from'../game/link.js';
const roster=n=>['host','slot1','slot2','slot3'].slice(0,n).map((id,i)=>({id,profile:{name:id,avatar:'wissem'},ready:true}));
test('2v2 requires exactly four players',()=>{assert.throws(()=>new LocalMatch({mode:'teams',roster:roster(3)}));assert.equal(new LocalMatch({mode:'teams',roster:roster(4)}).players.length,4);});
test('duplicate or injected player identifiers rejected',()=>{assert.throws(()=>new LocalMatch({roster:[{id:'host'},{id:'host'}]}));assert.throws(()=>new LocalMatch({roster:[{id:'host'},{id:'admin'}]}));});
test('input sanitizer rejects positions, scores and unbounded directions',()=>{const x=cleanInput({axis:999,aim:NaN,x:5000,score:999999,attack:'true',knife:true});assert.equal(x.axis,1);assert.equal(x.aim,0);assert.equal(x.x,undefined);assert.equal(x.score,undefined);assert.equal(x.attack,false);assert(x.knife);});
test('host rejects duplicate, stale and implausible input sequence',()=>{const m=new LocalMatch({roster:roster(2)});assert(m.input('slot1',{seq:1,input:{axis:1}}));assert(!m.input('slot1',{seq:1,input:{axis:1}}));assert(!m.input('slot1',{seq:0,input:{}}));assert(!m.input('slot1',{seq:1e9,input:{}}));assert(!m.input('admin',{seq:2,input:{}}));});
test('countdown freezes movement; stale held input releases',()=>{const m=new LocalMatch({mode:'ffa',roster:roster(2)});const x=m.players[1].run.player.x;m.input('slot1',{seq:1,input:{axis:1}});for(let i=0;i<60;i++)m.step();assert.equal(m.players[1].run.player.x,x);for(let i=0;i<125;i++)m.step();assert.equal(m.players[1].run.player.x,x);});
test('FFA uses host-owned melee hits and credits a knockout once',()=>{const m=new LocalMatch({mode:'ffa',roster:roster(2)});m.countdown=0;const[a,b]=m.players;Object.assign(a.run.player,{x:200,y:436,facing:1,invincible:0});Object.assign(b.run.player,{x:250,y:436,invincible:0,hp:2});for(let i=0;i<30;i++){m.input('host',{seq:i,input:{attack:true}});m.step();}assert.equal(a.kills,1);assert.equal(b.deaths,1);assert(b.run.player.deadFor>0||b.run.player.invincible>0);});
test('2v2 never damages a teammate',()=>{const m=new LocalMatch({mode:'teams',roster:roster(4)});m.countdown=0;const a=m.players[0],b=m.players[2];Object.assign(a.run.player,{x:200,y:436,facing:1,invincible:0});Object.assign(b.run.player,{x:250,y:436,invincible:0});for(let i=0;i<90;i++){m.input('host',{seq:i,input:{attack:true,skill:true,pet:true,summon:true}});m.step();}assert.equal(b.run.player.hp,6);assert.equal(a.run.summon,null);assert.equal(a.run.stats.skills,0);});
test('knives can hit opponents and spent ammunition is limited',()=>{const m=new LocalMatch({mode:'ffa',roster:roster(2)});m.countdown=0;const[a,b]=m.players;Object.assign(a.run.player,{x:200,y:436,facing:1,invincible:0});Object.assign(b.run.player,{x:400,y:436,invincible:0});for(let i=0;i<65;i++){m.input('host',{seq:i,input:{knife:true}});m.step();}assert(a.run.player.knives<12);assert(b.run.hits>=1);});
test('three-minute score match resolves a real tie',()=>{const m=new LocalMatch({mode:'teams',roster:roster(4)});m.time=183;m.countdown=0;m.step();assert(m.finished);assert(m.result.tie);assert.equal(m.result.winner,null);});
test('solo together has independent boss health on each client',()=>{const m=new LocalMatch({mode:'together',roster:roster(4)});m.players[0].run.boss.hp=10;assert.notEqual(m.players[1].run.boss.hp,10);assert.equal(m.players[0].run.petId,null);});
test('snapshot produces renderer-ready actual peers and rejects unknown recipients',()=>{const m=new LocalMatch({mode:'ffa',roster:roster(4)});const s=m.snapshot(),v=snapshotView(s,'slot1');assert.equal(v.remotePlayers.length,3);assert.equal(v.localPvp,true);assert.equal(snapshotView(s,'other'),null);assert(Buffer.byteLength(JSON.stringify(s))<32768);});
function wired(n=4){const out=[],sessions={};for(const id of ['host','slot1','slot2','slot3'].slice(0,n))sessions[id]=new NearbySession({profile:{name:id},send:(to,msg)=>out.push({from:id,to,msg}),onError:()=>{}});const flush=()=>{for(let guard=0;out.length&&guard<1000;guard++){const{from,to,msg}=out.shift();const remote=sessions[to];remote.receive(from==='host'?'host':from,JSON.stringify(msg));}};sessions.host.hostLobby();for(const id of Object.keys(sessions).slice(1)){sessions[id].prepareJoin(sessions.host.roomCode);sessions.host.connected(id);sessions[id].connected('host');}flush();return{sessions,flush,out};}
test('four independent session instances handshake, ready, start and synchronize',()=>{const{sessions:s,flush}=wired();assert.equal(s.host.roster.length,4);s.host.configure('teams',2,'nightmare');flush();for(const id of ['slot1','slot2','slot3'])s[id].ready(true);flush();s.host.start();flush();for(let i=0;i<240;i++){for(const id of ['slot1','slot2','slot3'])s[id].step({axis:1,attack:i%3===0},1/60);flush();s.host.step({},1/60);flush();}assert.equal(s.slot1.state,'playing');assert(s.slot1.snapshot.tick>200);assert.equal(s.slot1.snapshot.players.length,4);assert.equal(s.slot2.snapshot.protocol,LINK_PROTOCOL);});
test('malformed messages, unknown transport peers and wrong protocol rejected',()=>{const{s:unused,...x}=wired(2);const s=x.sessions;assert(!s.host.receive('slot1','{'));assert(!s.host.receive('slot3',JSON.stringify({type:'hello',protocol:4})));assert(!s.host.receive('slot1',JSON.stringify({type:'ready',protocol:3,ready:true})));assert(!s.host.receive('slot1','x'.repeat(40000)));});
test('disconnect cancels competitive play instead of inventing a winner',()=>{const{sessions:s,flush}=wired(2);s.slot1.ready(true);flush();s.host.start();flush();s.host.disconnected('slot1');assert.equal(s.host.state,'ended');assert.equal(s.host.match,null);});
test('rematch rotates session ID and rejects old input packets',()=>{const{sessions:s,flush}=wired(2);s.slot1.ready(true);flush();s.host.start();flush();const old=s.host.sessionId;s.host.match.finish();s.host.state='results';s.host.rematch();flush();s.slot1.ready(true);flush();s.host.start();flush();assert.notEqual(s.host.sessionId,old);assert(!s.host.receive('slot1',JSON.stringify({type:'input',protocol:4,session:old,seq:20,input:{axis:1}})));});

// Host renderer-safety checks, not an anti-cheat claim.
test('malformed remote snapshots cannot allocate excessive hearts or smuggle profile markup',async()=>{
 const{validSnapshot}=await import('../game/arena.js');const m=new LocalMatch({mode:'ffa',roster:[{id:'host'},{id:'slot1'}]});let s=m.snapshot();assert.equal(validSnapshot(s),true);
 s.players[0].player.maxHp=1e8;assert.equal(validSnapshot(s),false);s=m.snapshot();s.players[1].profile.frame='" onload="alert(1)';assert.equal(validSnapshot(s),false);s=m.snapshot();s.players[1].shots=Array(200).fill({x:0,y:0});assert.equal(validSnapshot(s),false);
});
