import test from 'node:test';import assert from 'node:assert/strict';
import {makeLevel,createRun,stepRun,meleeAttack} from '../game/engine.js';import {validatePlacements,PlacementGrid,spawnPickup} from '../game/placement.js';import {sanitizeSave,defaultSave} from '../game/progress.js';import {combatProfile} from '../game/combat-profiles.js';
for(let id=0;id<15;id++)test(`World ${id+1} occupancy and rare power budget`,()=>{const l=makeLevel(id);assert.deepEqual(validatePlacements(l),[]);assert(l.pickups.length<=8);assert(l.chambers.every(c=>c.sigils.length));});
test('dynamic pickup cannot share an occupied cell or spawn inside terrain',()=>{const l=makeLevel(0),o=l.coins[0];const p=spawnPickup(l,{...o,type:'heart'});assert(!p||Math.floor(p.x/40)!==Math.floor(o.x/40)||Math.floor(p.y/40)!==Math.floor(o.y/40));const grid=new PlacementGrid(l);assert(!grid.canPlace({x:40,y:500,w:28,h:28}));});
test('crouch preserves feet and cannot stand into a low ceiling',()=>{const r=createRun();r.player.grounded=true;stepRun(r,{crouch:true});assert.equal(r.player.h,26);assert.equal(r.player.y+r.player.h,480);r.level.tiles[10][3]=5;r.player.y=440;r.player.h=26;r.player.grounded=true;stepRun(r,{});assert.equal(r.player.h,26);r.level.tiles[10][3]=0;stepRun(r,{});assert.equal(r.player.h,44);});
test('discovery migration preserves known ids and rejects invalid ids',()=>{assert.deepEqual(defaultSave().discoveredPowerUps,[]);assert.deepEqual(sanitizeSave({discoveredPowerUps:['heart','heart','bogus']}).discoveredPowerUps,['heart']);});
for(const [hero,kind]of [['loey','arrow'],['yakine','arcane'],['youssef','bolt']])test(`${hero} anticipates then launches weapon projectile`,()=>{const r=createRun(0,hero);r.level.enemies=[];assert(meleeAttack(r));assert.equal(r.shots.length,0);for(let i=0;i<20;i++)stepRun(r,{});assert(r.shots.some(s=>s.kind===kind));});
test('heavy guardian and agile rogue have distinct acceleration profiles; PvP stays normalized',()=>{assert(combatProfile({character:'garsi'}).accel<combatProfile({character:'taky'}).accel);assert.deepEqual(combatProfile({character:'garsi',normalizedCombat:true}),combatProfile({character:'taky',normalizedCombat:true}));});

import {validateRoute} from '../scripts/validate-routes.mjs';
for(let i=0;i<15;i++)test(`World ${i+1}: required seals, underground return and stargate reachable`,()=>{assert.deepEqual(validateRoute(makeLevel(i)).issues,[]);});

test('seal lift waits for its passenger and safely carries them to the restored surface bridge',()=>{const r=createRun();const lift=r.level.lifts[0];r.level.chambers[0].complete=true;r.stageIndex=1;r.level.chambers[1].sigils.forEach(s=>s.taken=true);r.player.x=lift.x-95;r.player.y=1076;r.player.grounded=true;stepRun(r,{interact:true});assert(!lift.active);r.player.x=lift.x+20;r.player.y=1076;r.player.grounded=true;for(let i=0;i<400;i++)stepRun(r,{interact:true});assert(lift.active);assert.equal(lift.y,480);assert(r.player.y<=436);assert(r.level.bridgeOpened);});
