/** Version 3 gameplay/progression regressions. Test fixtures deliberately isolate
 * individual mechanics. Only the final traversal group uses unmodified levels
 * with ordinary inputs; fixture positioning is not presented as playtesting. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {HEROES,WORLDS,ENEMY_TYPES,POWERS,PETS,GROUND,dailyQuests,heroById} from '../game/data.js';
import {makeLevel,makeEnemy,createRun,stepRun,activateSkill,activatePetSkill,applyPower,damagePlayer,defeat,stageRates,advanceEndless,objectiveResults,runDistance,tileAt} from '../game/engine.js';
import {defaultSave,sanitizeSave,loadSave,saveProgress,SAVE_KEY,bankRunStats,recordRun,claimQuest,unlockTrail,starsTotal,refreshDay,utcDay,equipPet} from '../game/progress.js';
import {pilot} from './pilot.mjs';
const frames=(r,n,input={})=>{for(let i=0;i<n;i++)stepRun(r,input);return r;};
const clean=(hero='wissem',pet=null,mode='campaign')=>{const r=createRun(0,hero,mode,0,pet);r.level.enemies=[];r.level.coins=[];r.level.pickups=[];r.level.chests=[];r.level.crates=[];r.level.shrines=[];r.level.buried=[];r.level.eggs=[];frames(r,3);return r;};
const near=(a,b,epsilon=.0001)=>assert.ok(Math.abs(a-b)<epsilon,`${a} ≠ ${b}`);
class MemoryStorage {constructor(){this.data=new Map();}getItem(k){return this.data.get(k)||null;}setItem(k,v){this.data.set(k,String(v));}}

test('content: 15 worlds, 8 named heroes, 16 unique skills, 13 monsters, 14 powers, 7 pets',()=>{
 assert.equal(WORLDS.length,15);assert.deepEqual(HEROES.map(h=>h.name),['Wissem','Kossay','Yakine','Taky','Garsi','Tounsi','Youssef','Loey']);assert.equal(new Set(HEROES.flatMap(h=>h.skills.map(s=>s.id))).size,16);assert.equal(ENEMY_TYPES.length,13);assert.equal(POWERS.length,14);assert.equal(PETS.filter(p=>p.rarity==='super').length,5);assert.equal(PETS.filter(p=>p.rarity==='super rare').length,2);
});
for(const w of WORLDS)test(`map ${w.id+1}: exactly five times the v2 width, populated sectors and safe checkpoint floors`,()=>{
 const l=makeLevel(w.id);assert.equal(l.cols,w.baseLength*5);assert.equal(w.lengthMultiplier,5);assert.equal(l.checkpoints.length,10);assert.equal(l.chests.length,10);assert.equal(l.crates.length,5);assert.equal(l.shrines.length,5);assert.ok(l.enemies.length>=35);assert.ok(l.pickups.length>=30);assert.ok(l.coins.length>=w.coinGoal);assert.equal(tileAt(l,3,12),1);
 for(const c of l.checkpoints)assert.equal(tileAt(l,Math.floor(c.x/40),12),1);
 for(let sec=0;sec<5;sec++){const lo=sec*w.baseLength*40,hi=(sec+1)*w.baseLength*40;assert.ok(l.enemies.some(e=>e.x>=lo&&e.x<hi));assert.ok(l.pickups.some(e=>e.x>=lo&&e.x<hi));}
});
test('deterministic level generation',()=>assert.deepEqual(makeLevel(8,23,true),makeLevel(8,23,true)));
test('map IDs clamp safely',()=>{assert.equal(makeLevel(-1).id,0);assert.equal(makeLevel(999).id,14);assert.equal(makeLevel(NaN).id,0);});
test('monster budgets increase and power budgets never decrease across the 15 worlds',()=>{let en=0,pw=0;for(const w of WORLDS){const l=makeLevel(w.id);assert.ok(l.enemies.length>en);assert.ok(l.pickups.length>=pw);en=l.enemies.length;pw=l.pickups.length;}});
test('all thirteen monsters occur in actual generated levels',()=>assert.deepEqual([...new Set(WORLDS.flatMap(w=>makeLevel(w.id).enemies.map(e=>e.type)))].sort(),[...ENEMY_TYPES].sort()));
test('all pet rescue eggs exist in their documented map and on safe floor',()=>{for(const pet of PETS){const l=makeLevel(pet.unlockWorld),e=l.eggs.find(e=>e.id===pet.id);assert.ok(e);assert.ok(tileAt(l,Math.floor(e.x/40),12));assert.ok(e.x>120&&e.x<l.goal.x);}});
test('idle spawn is safe',()=>{const r=createRun();frames(r,300);assert.equal(r.player.hp,3);assert.equal(r.player.x,120);assert.equal(r.player.y,436);});
test('ordinary movement remains finite and changes direction',()=>{const r=clean();frames(r,45,{right:true});assert.ok(r.player.x>300);frames(r,45,{left:true});assert.ok(Number.isFinite(r.player.y));assert.equal(r.player.facing,-1);});
test('held jump rises farther than a short tap',()=>{const high=n=>{const r=clean();let y=r.player.y;for(let i=0;i<45;i++){stepRun(r,{jump:i<n});y=Math.min(y,r.player.y);}return y;};assert.ok(high(30)<high(2)-50);});
test('invalid dt guarded and excessive dt clamped',()=>{const r=clean();stepRun(r,{right:true},NaN);assert.ok(Number.isFinite(r.player.x));const x=r.player.x;stepRun(r,{right:true},10);assert.ok(r.player.x-x<25);});

const effects={gravity:r=>r.player.gravity===4&&r.player.vy<0,bomba:r=>r.bombs.length===1,fang:r=>r.player.dash>0&&r.player.invincible>0,snare:r=>r.traps[0]?.life===7,orbit:r=>r.player.orbit===6,chrono:r=>r.slow===5,shadow:r=>r.player.x>120&&r.player.veil===1.8,blades:r=>r.shots.length===5,bastion:r=>r.player.bastion===4,quake:r=>r.level.enemies.every(e=>!e.alive),sirocco:r=>r.player.spin===3&&r.player.magnet===3,vault:r=>r.player.vy===-900&&r.player.glide===3,turret:r=>r.turrets[0]?.life===8,overclock:r=>r.player.overclock===7,arrows:r=>r.shots.length===3&&r.shots.every(s=>s.homing),windwalk:r=>r.player.windwalk===6&&r.player.airJump};
for(const h of HEROES)for(let slot=0;slot<2;slot++)test(`${h.name} / ${h.skills[slot].name}: effect and independent cooldown`,()=>{
 const r=clean(h.id);r.level.enemies=[makeEnemy('golem',190,1)];assert.equal(activateSkill(r,slot),true);assert.ok(effects[h.skills[slot].id](r));assert.equal(r.player[slot?'cooldown2':'cooldown'],h.skills[slot].cooldown);assert.equal(activateSkill(r,slot),false);assert.equal(r.stats.skills,1);assert.equal(activateSkill(r,1-slot),true);assert.equal(r.stats.skills,2);
});
test('holding either hero button never repeats without release',()=>{for(const slot of ['skill','skill2']){const r=clean();frames(r,850,{[slot]:true});assert.equal(r.stats.skills,1);stepRun(r);stepRun(r,{[slot]:true});assert.equal(r.stats.skills,2);}});
test('skills refuse invalid slots and dead/completed/failed runs',()=>{const r=clean();assert.equal(activateSkill(r,5),false);r.complete=true;assert.equal(activateSkill(r),false);r.complete=false;r.failed=true;assert.equal(activateSkill(r,1),false);r.failed=false;r.player.deadFor=.2;assert.equal(activateSkill(r),false);});
test('Wissem crowd fury speeds recharge and increases Bomba radius',()=>{const r=clean();for(let i=0;i<9;i++)r.level.enemies.push(makeEnemy('slime',250+i*9,i));r.player.cooldown=10;stepRun(r);assert.equal(r.player.crowd,3);near(r.player.cooldown,10-1.75/60);activateSkill(r,1);assert.equal(r.bombs[0].radius,295);});
test('Bomba explodes via simulation and destroys nearby enemies/bricks',()=>{const r=clean();r.level.enemies=[makeEnemy('golem',280,1)];r.level.tiles[10][7]=2;activateSkill(r,1);frames(r,45);assert.equal(r.bombs.length,0);assert.equal(r.level.enemies[0].alive,false);assert.equal(r.level.tiles[10][7],0);});
test('Chrono slows hostile projectiles without slowing hero movement',()=>{const a=clean('yakine'),b=clean('yakine');for(const r of[a,b])r.shots=[{owner:'foe',x:350,y:400,w:10,h:10,vx:100,vy:0,life:10}];activateSkill(a,1);stepRun(a,{right:true});stepRun(b,{right:true});assert.ok(a.shots[0].x-350<(b.shots[0].x-350)*.3);assert.equal(a.player.x,b.player.x);});
test('Iron bastion reflects an incoming projectile',()=>{const r=clean('garsi');activateSkill(r);r.shots=[{owner:'foe',x:127,y:442,w:10,h:10,vx:-100,vy:0,life:10}];stepRun(r);assert.equal(r.shots[0].owner,'hero');assert.equal(r.player.hp,3);});
test('airborne Quake lands and clears its slam state',()=>{const r=clean('garsi');r.player.y-=80;r.player.grounded=false;activateSkill(r,1);assert.ok(r.player.slam);frames(r,12);assert.equal(r.player.slam,false);});
test('Pocket turret actually fires and defeats a target',()=>{const r=clean('youssef');r.level.enemies=[makeEnemy('golem',320,1)];activateSkill(r);frames(r,120);assert.equal(r.level.enemies[0].alive,false);});
test('homing seeker arrows actually defeat a moving enemy',()=>{const r=clean('loey');r.level.enemies=[makeEnemy('beetle',350,1)];activateSkill(r);frames(r,40);assert.equal(r.level.enemies[0].alive,false);});

const powCheck={shield:r=>r.player.shield,heart:r=>r.player.hp===2,spark:r=>r.player.spark===7,magnet:r=>r.player.magnet===12,double:r=>r.player.double===12,haste:r=>r.player.haste===10,nova:r=>r.player.orbit===10,fire:r=>r.player.fire===12,ice:r=>r.player.ice===12,giant:r=>r.player.maxHp===5&&r.player.hp===3,thunder:r=>r.player.thunder===12,phase:r=>r.player.phase===6,rescue:r=>r.player.rescue===1,bomb:r=>r.level.enemies[0].alive===false};
for(const power of POWERS)test(`pickup ${power.name}: applies its configured mechanic`,()=>{const r=clean();r.player.hp=1;r.level.enemies=[makeEnemy('slime',200,1)];assert.equal(applyPower(r,power.id),true);assert.ok(powCheck[power.id](r));assert.equal(r.stats.powers,1);});
test('unknown pickup has no side effect',()=>{const r=clean();assert.equal(applyPower(r,'unknown'),false);assert.equal(r.stats.powers,0);});
test('giant heart expires after 20s and clamps health to normal maximum',()=>{const r=clean();applyPower(r,'giant');frames(r,1201);assert.equal(r.player.maxHp,3);assert.equal(r.player.hp,3);});
test('fire fruit shoots, ice freezes, thunder strikes through actual ticks',()=>{for(const pow of ['fire','ice','thunder']){const r=clean();r.level.enemies=[makeEnemy('golem',330,1)];applyPower(r,pow);if(pow==='ice')assert.equal(r.level.enemies[0].frozen,3);frames(r,150);assert.equal(r.level.enemies[0].alive,false,pow);}});
test('phase crystal passes breakable blocks but remains on solid ground',()=>{const r=clean();r.level.tiles[10][4]=2;r.level.tiles[11][4]=2;applyPower(r,'phase');frames(r,30,{right:true});assert.ok(r.player.x>200);assert.equal(r.player.y,436);});
test('phase expiration inside a block resolves to non-overlapping space',()=>{const r=clean();r.player.x=164;r.player.phase=.001;r.level.tiles[11][4]=2;stepRun(r);assert.notEqual(Math.floor(r.player.x/40),4);assert.equal(r.player.phase,0);});
test('rescue feather prevents one fall but not the next',()=>{const r=clean();applyPower(r,'rescue');damagePlayer(r,true);assert.equal(r.player.lives,3);assert.equal(r.player.rescue,0);damagePlayer(r,true);assert.equal(r.player.lives,2);});
test('shield blocks exactly one damaging hit',()=>{const r=clean();applyPower(r,'shield');damagePlayer(r);assert.equal(r.player.hp,3);assert.equal(r.player.shield,false);r.player.invincible=0;damagePlayer(r);assert.equal(r.player.hp,2);});
test('a temporary invulnerability power never prevents a cliff death',()=>{const r=clean();applyPower(r,'spark');damagePlayer(r);assert.equal(r.player.hp,3);damagePlayer(r,true);assert.equal(r.player.lives,2);});
test('chests, crates and shrines open once and produce collectible power-ups',()=>{for(const kind of ['chests','crates','shrines']){const r=clean();r.level[kind]=[{x:122,y:442,w:32,h:36,opened:false,type:'ice'}];stepRun(r);assert.equal(r.level[kind][0].opened,true);assert.equal(r.level.pickups.length,1);stepRun(r);assert.equal(r.level.pickups.length,1);}});
test('overhead cache produces a visible pickup and becomes a used block',()=>{const r=clean();r.level.tiles[9][3]=3;r.level.blocks.push({x:3,y:9,power:'ice'});frames(r,20,{jump:true});assert.equal(r.level.tiles[9][3],4);assert.ok(r.level.pickups.some(p=>p.type==='ice'));});
test('coin magnet moves coins, double gold doubles value not count',()=>{const r=clean();r.player.magnet=10;const c={x:290,y:442,w:18,h:24,taken:false};r.level.coins=[c];stepRun(r);assert.ok(c.x<290);r.player.double=10;r.level.coins=[{x:125,y:442,w:18,h:24,taken:false}];stepRun(r);assert.equal(r.coinsEarned,2);assert.equal(r.coinCount,1);});

// Exact rare-pet contracts, including timer boundaries and transition behavior.
test('Dragon Scales: exactly 15 actual contacts kill enemies with zero damage',()=>{
 const r=clean('wissem','dragon');assert.equal(r.player.scales,15);
 for(let i=0;i<15;i++){const e=makeEnemy('golem',120,100+i);e.vx=0;r.level.enemies=[e];r.player.x=120;r.player.y=436;r.player.vx=r.player.vy=0;stepRun(r);assert.equal(e.alive,false);assert.equal(r.player.hp,3);assert.equal(r.player.scales,14-i);}
 r.player.invincible=0;const e=makeEnemy('golem',120,120);e.vx=0;r.level.enemies=[e];stepRun(r);assert.ok(e.alive);assert.equal(r.player.hp,2);
});
test('Dragon Scales does not refill at checkpoints or endless transitions',()=>{const r=clean('wissem','dragon','endless');r.player.scales=4;advanceEndless(r);assert.equal(r.player.scales,4);r.player.x=r.level.checkpoints[0].x;stepRun(r);assert.equal(r.player.scales,4);});
test('Dragon Breath multiplies every kill award by exactly 3, not coins',()=>{
 const a=clean('wissem','dragon'),b=clean('wissem','dragon');activatePetSkill(a);
 for(let i=0;i<10;i++){const oldA=a.score,oldB=b.score;defeat(a,makeEnemy(i%2?'golem':'slime',400,i),100);defeat(b,makeEnemy(i%2?'golem':'slime',400,i),100);assert.equal(a.score-oldA,(b.score-oldB)*3);}
 const sa=a.score,sb=b.score;for(const r of[a,b]){r.level.coins=[{x:125,y:442,w:18,h:24,taken:false}];stepRun(r);}assert.equal(a.score-sa,b.score-sb);
});
test('Dragon Breath lasts 45 seconds and has its own longer cooldown',()=>{const r=clean('wissem','dragon');activatePetSkill(r);assert.equal(r.player.breath,45);frames(r,2699);assert.ok(r.player.breath>0);frames(r,2);assert.equal(r.player.breath,0);assert.ok(r.player.petCooldown>44);assert.equal(activatePetSkill(r),false);});
test('Flood clears the entire current map, including spawn warnings and hostile shots',()=>{const r=createRun(14,'wissem','campaign',0,'orca');r.level.enemies[0].warning=100;r.shots=[{owner:'foe'},{owner:'hero'}];const count=r.level.enemies.length;assert.equal(activatePetSkill(r),true);assert.equal(r.stats.kills,count);assert.ok(r.level.enemies.every(e=>!e.alive));assert.ok(r.shots.every(s=>s.owner!=='foe'));assert.equal(r.player.flood,45);});
test('Flood suppresses added enemies and dynamic spawns for 45s, then stops',()=>{const r=clean('wissem','orca','endless');activatePetSkill(r);r.player.x=1100;stepRun(r);assert.ok(!r.level.enemies.some(e=>e.alive));r.player.x=120;const e=makeEnemy('golem',120,4);r.level.enemies=[e];stepRun(r);assert.equal(e.alive,false);frames(r,2700);assert.equal(r.player.flood,0);const alive=makeEnemy('slime',600,5);r.level.enemies=[alive];stepRun(r);assert.equal(alive.alive,true);});
test('Orca Prince supports every cliff without modifying the terrain tiles',()=>{const r=clean('wissem','orca');const tiles=JSON.stringify(r.level.tiles);activatePetSkill(r,1);for(const tx of r.level.cfg.gaps){r.player.x=tx*40+4;r.player.y=GROUND-r.player.h+35;r.player.vy=300;stepRun(r);assert.equal(r.player.y,GROUND-r.player.h);assert.equal(r.player.lives,3);}assert.equal(JSON.stringify(r.level.tiles),tiles);});
test('Orca Prince rescues a current fall and runs for exactly 45s',()=>{const r=clean('wissem','orca');r.player.y=690;activatePetSkill(r,1);assert.equal(r.player.y,436);assert.equal(r.player.prince,45);frames(r,2699);assert.ok(r.player.prince>0);frames(r,2);assert.equal(r.player.prince,0);damagePlayer(r,true);assert.equal(r.player.lives,2);});
test('Orca abilities have independent buttons/cooldowns and distinct protections',()=>{const a=clean('wissem','orca');activatePetSkill(a);assert.equal(a.player.prince,0);damagePlayer(a,true);assert.equal(a.player.lives,2);const b=clean('wissem','orca');activatePetSkill(b,1);assert.equal(b.player.flood,0);damagePlayer(b);assert.equal(b.player.hp,2);assert.equal(activatePetSkill(b,0),true);assert.equal(b.player.petCooldown,100);assert.ok(b.player.petCooldown2>0);});
test('rare buffs and cooldowns persist across an endless world boundary',()=>{const r=createRun(14,'wissem','endless',14,'orca');activatePetSkill(r);activatePetSkill(r,1);advanceEndless(r);assert.equal(r.worldId,0);assert.equal(r.stage,15);assert.equal(r.player.flood,45);assert.equal(r.player.prince,45);assert.equal(r.player.petCooldown,100);assert.ok(r.level.enemies.every(e=>!e.alive));});
test('ordinary pets cannot invoke unowned rare abilities',()=>{for(const pet of PETS.filter(p=>p.rarity==='super')){const r=clean('wissem',pet.id);assert.equal(activatePetSkill(r),false);assert.equal(activatePetSkill(r,1),false);}});
test('Wolf attacks automatically and waits for its bite interval',()=>{const r=clean('wissem','wolf'),e=makeEnemy('golem',230,1);r.level.enemies=[e];stepRun(r);assert.equal(e.hp,1);stepRun(r);assert.equal(e.hp,1);frames(r,110);assert.equal(e.alive,false);});
test('Eagle reveals treasure and extends coin attraction',()=>{const r=clean('wissem','eagle');r.level.buried=[{x:350,y:450,w:28,h:28,opened:false}];const c={x:210,y:442,w:18,h:24,taken:false};r.level.coins=[c];stepRun(r);assert.ok(r.level.buried[0].revealed);assert.ok(c.x<210);});
test('Mole rewards new forward distance, never idle farming',()=>{const r=clean('wissem','mole');r.furthest=1000;stepRun(r);assert.equal(r.coinsEarned,8);frames(r,240);assert.equal(r.coinsEarned,8);r.furthest=2000;stepRun(r);assert.equal(r.coinsEarned,16);});
test('Fox fires at enemies and produces a distance-gated supply',()=>{const r=clean('wissem','fox');r.level.enemies=[makeEnemy('beetle',320,1)];stepRun(r);assert.ok(r.shots.some(s=>s.kind==='fire'));r.furthest=1900;stepRun(r);assert.equal(r.level.pickups.length,1);});
test('Turtle blocks one hit, regrows guard after 18s, does not protect a cliff',()=>{const r=clean('wissem','turtle');damagePlayer(r);assert.equal(r.player.hp,3);assert.equal(r.petState.guard,false);frames(r,1081);assert.equal(r.petState.guard,true);damagePlayer(r,true);assert.equal(r.player.lives,2);});
test('a rescue egg is collected once and safely persisted',()=>{const r=clean(),s=defaultSave();r.level.eggs=[{id:'wolf',x:122,y:435,w:35,h:45,taken:false}];stepRun(r);assert.deepEqual(r.petsFound,['wolf']);bankRunStats(s,r);bankRunStats(s,r);assert.deepEqual(s.pets,['wolf']);assert.equal(s.pet,'wolf');stepRun(r);assert.equal(r.petsFound.length,1);});
test('practice can test rare pets but awards no pets, stars, gold, stats, or records',()=>{const s=defaultSave(),r=createRun(14,'wissem','practice',0,'orca'),before=JSON.stringify(s);r.petsFound=['orca','dragon'];r.complete=true;r.coinsEarned=900;r.score=20000;r.stats.coins=900;bankRunStats(s,r);recordRun(s,r);assert.equal(JSON.stringify(s),before);});
test('pet equipment refuses locked pets and supports unequip',()=>{const s=defaultSave();assert.equal(equipPet(s,'dragon'),false);s.pets=['wolf'];assert.equal(equipPet(s,'wolf'),true);assert.equal(equipPet(s,null),true);assert.equal(s.pet,null);});

test('campaign has three attempts; endless has one',()=>{const r=clean();for(let i=0;i<3;i++){r.player.deadFor=0;damagePlayer(r,true);}assert.ok(r.failed);const e=clean('wissem',null,'endless');damagePlayer(e,true);assert.ok(e.failed);});
test('slime stomps die and spiked enemies cannot be stomped',()=>{for(const type of ['slime','spiker']){const r=clean(),e=makeEnemy(type,120,0);r.level.enemies=[e];r.player.y=e.y-r.player.h-1;r.player.vy=200;stepRun(r);assert.equal(e.alive,type==='spiker');}});
test('endless loop 15→1 keeps score, distance, health and pet without retaining old levels',()=>{const r=createRun(0,'wissem','endless',0,'dragon');r.player.hp=2;r.player.scales=7;r.player.elapsed=40;r.score=500;let old=r.level;for(let i=0;i<15;i++){advanceEndless(r);assert.notEqual(r.level,old);old=r.level;assert.ok(r.level.enemies.length<300);}assert.equal(r.stage,15);assert.equal(r.worldId,0);assert.equal(r.player.hp,2);assert.equal(r.player.scales,7);assert.equal(r.petId,'dragon');assert.equal(r.player.elapsed,40);assert.ok(r.score>500&&runDistance(r)>10000);});
test('distance-driven endless spawn intervals tighten but remain capped',()=>{let prev=stageRates(0);for(let i=1;i<300;i++){const n=stageRates(i);assert.ok(n.enemyGap<=prev.enemyGap&&n.enemyGap>=220);assert.ok(n.powerGap<=prev.powerGap&&n.powerGap>=380);assert.ok(n.speedScale<=2.8);prev=n;}const r=clean('wissem',null,'endless');frames(r,400);assert.equal(r.level.enemies.length,0);r.player.x=1100;stepRun(r);assert.ok(r.level.enemies.some(e=>e.dynamic));});
test('contact with campaign portal completes; endless advances',()=>{const r=clean();r.player.x=r.level.goal.x;stepRun(r);assert.ok(r.complete);const e=clean('wissem',null,'endless');e.player.x=e.level.goal.x;stepRun(e);assert.equal(e.stage,1);assert.equal(e.complete,false);});
test('failed run earns no campaign stars',()=>{const r=createRun();r.coinCount=99999;assert.ok(objectiveResults(r).every(o=>!o.done));});
test('medals accumulate across replays and rewards are idempotent',()=>{const s=defaultSave(),r=createRun();r.complete=true;r.coinCount=0;r.knockouts=0;r.score=500;recordRun(s,r);assert.deepEqual(s.maps[0].stars,[true,false,true]);const before=JSON.stringify(s);recordRun(s,r);assert.equal(JSON.stringify(s),before);const r2=createRun();r2.complete=true;r2.coinCount=WORLDS[0].coinGoal;r2.knockouts=2;recordRun(s,r2);assert.equal(starsTotal(s),3);});
test('stat banking counts deltas only',()=>{const s=defaultSave(),r=createRun();r.coinsEarned=10;r.stats.coins=10;bankRunStats(s,r);bankRunStats(s,r);assert.equal(s.gold,10);r.coinsEarned=13;r.stats.coins=13;bankRunStats(s,r);assert.equal(s.gold,13);});
test('mission reward requires target and cannot be claimed twice',()=>{const s=defaultSave();assert.equal(claimQuest(s,'coins100'),0);s.totals.coins=100;assert.equal(claimQuest(s,'coins100'),150);assert.equal(claimQuest(s,'coins100'),0);});
test('daily rollover resets only daily stats and claims',()=>{const s=defaultSave(),q=dailyQuests(s.daily.day)[0];s.daily.stats.coins=q.target;assert.ok(claimQuest(s,q.id,true)>0);assert.equal(claimQuest(s,q.id,true),0);s.daily.day='2000-01-01';refreshDay(s);assert.equal(s.daily.day,utcDay());assert.equal(s.daily.stats.coins,0);assert.equal(s.daily.claims.length,0);});
test('cosmetic trails only spend earned coins once',()=>{const s=defaultSave();s.gold=450;assert.equal(unlockTrail(s,'mint'),true);assert.equal(s.gold,50);unlockTrail(s,'mint');assert.equal(s.gold,50);});
test('top eight endless records retain actual attempts only',()=>{const s=defaultSave();assert.equal(s.endless.runs.length,0);for(let i=0;i<12;i++){const r=createRun(0,'wissem','endless');r.failed=true;r.score=i*100;recordRun(s,r);}assert.equal(s.endless.runs.length,8);assert.equal(s.endless.best,1100);});
test('v2 migration preserves currency, hero mapping, settings and clears; resets long-map records',()=>{const store=new MemoryStorage(),old=defaultSave();old.version=2;old.hero='nova';old.gold=1350;old.settings.music=false;old.maps[0]={clear:true,stars:[true,true,true],score:2000,time:40};old.endless.best=1234;const raw=JSON.stringify(old);store.setItem('super-wiss:odyssey-v2',raw);const result=loadSave(store);assert.ok(result.migrated);assert.equal(result.save.hero,'yakine');assert.equal(result.save.gold,1350);assert.equal(result.save.settings.music,false);assert.deepEqual(result.save.maps[0],{clear:true,stars:[true,false,false],score:0,time:null});assert.equal(result.save.endless.best,0);assert.equal(store.getItem('super-wiss:odyssey-v2'),raw);});
test('v3 storage round trip, backup recovery and pet ownership',()=>{const store=new MemoryStorage(),s=defaultSave();s.gold=42;s.pets=['dragon'];s.pet='dragon';saveProgress(store,s);s.gold=50;saveProgress(store,s);assert.equal(loadSave(store).save.gold,50);store.setItem(SAVE_KEY,'invalid');const recovered=loadSave(store);assert.ok(recovered.recovered);assert.equal(recovered.save.gold,42);assert.equal(recovered.save.pet,'dragon');});
test('malformed saves sanitize and unavailable storage is explicit',()=>{const s=sanitizeSave({hero:'<script>',gold:-8,xp:Infinity,pets:['oops','wolf','wolf'],pet:'orca',maps:[null]});assert.equal(s.hero,'wissem');assert.equal(s.gold,0);assert.equal(s.xp,0);assert.deepEqual(s.pets,['wolf']);assert.equal(s.pet,null);assert.equal(s.maps.length,15);const blocked={getItem(){throw Error()},setItem(){throw Error()}};assert.equal(loadSave(blocked).ephemeral,true);assert.equal(saveProgress(blocked,s),false);});

// Unmodified actual long maps, normal control inputs; companions are legal game
// choices (wolf/turtle were rescued in earlier worlds). These are not human QA.
for(let id=0;id<15;id++)test(`ordinary-input long-map completion ${id+1}: ${WORLDS[id].name}`,()=>{
 const hero=id===9?'loey':id===11?'taky':'wissem',pet=id===9?'wolf':id===13?'turtle':null;
 const r=createRun(id,hero,'campaign',0,pet);
 for(let i=0;i<35000&&!r.complete&&!r.failed;i++)stepRun(r,pilot(r));
 assert.equal(r.complete,true,`${hero}/${pet}: x=${Math.round(r.player.x)}, deaths=${r.knockouts}`);
 assert.ok(r.player.elapsed<300);assert.ok(Number.isFinite(r.score));
});
