import {makeLevel} from '../game/engine.js';import {validatePlacements} from '../game/placement.js';import fs from 'node:fs';
const T=40,W=28,H=44;
function blocked(l,x,y){if(x<0||x+W>l.width||y<0)return true;for(let yy=Math.floor(y/T);yy<=Math.floor((y+H-.01)/T);yy++)for(let xx=Math.floor(x/T);xx<=Math.floor((x+W-.01)/T);xx++)if(l.tiles[yy]?.[xx])return true;return false;}
export function routeGraph(l){const nodes=[],byKey=new Map();for(let y=1;y<l.tiles.length;y++)for(let x=0;x<l.cols;x++)if(l.tiles[y][x]&&!blocked(l,x*T+6,y*T-H)){const n={id:nodes.length,x:x*T+6,y:y*T-H,col:x,row:y,edges:[],actions:{}};nodes.push(n);byKey.set(x+','+y,n);}
 for(const n of nodes){for(const dir of [-1,1]){const q=byKey.get((n.col+dir)+','+n.row);if(q){n.edges.push(q.id);n.actions[q.id]={speed:dir*272,jump:false};}}for(const jump of [false,true])for(const speed of [-272,-190,-95,0,95,190,272]){if(!jump&&!speed)continue;let x=n.x,y=n.y,vx=0,vy=jump?-755:0;for(let i=0;i<240;i++){const dt=1/120;vx+=Math.sign(speed-vx)*Math.min(Math.abs(speed-vx),1450*.78*dt);let xx=x+vx*dt;if(!blocked(l,xx,y))x=xx;else vx=0;vy=Math.min(1050,vy+1940*dt);const yy=y+vy*dt;if(blocked(l,x,yy)){if(vy>0){const row=Math.floor((yy+H)/T),q=[Math.floor(x/T),Math.floor((x+W-.01)/T)].map(col=>byKey.get(col+','+row)).find(Boolean);if(q&&q.id!==n.id){n.edges.push(q.id);if(!n.actions[q.id])n.actions[q.id]={speed,jump};}break;}vy=0;}else y=yy;if(y>l.height)break;}}
 n.edges=[...new Set(n.edges)];}return {nodes,byKey};}
function reachable(graph,start,maxX=Infinity){const found=new Set([start.id]),queue=[start];for(let i=0;i<queue.length;i++)for(const id of queue[i].edges){const n=graph.nodes[id];if(n.x<=maxX&&!found.has(id)){found.add(id);queue.push(n);}}return found;}
export function validateRoute(l){const graph=routeGraph(l),start=graph.nodes.reduce((a,b)=>Math.hypot(b.x-l.spawn.x,b.y-l.spawn.y)<Math.hypot(a.x-l.spawn.x,a.y-l.spawn.y)?b:a),all=reachable(graph,start),issues=[];
 for(const c of l.chambers){const allowed=reachable(graph,start,c.gateX-28);for(const z of c.sigils){const near=graph.nodes.filter(n=>n.x<z.x+z.w&&n.x+W>z.x&&n.y<z.y+z.h&&n.y+H>z.y);if(!near.some(n=>allowed.has(n.id)))issues.push('Unreachable seal '+c.id);if(c.id===1&&near.length){const ret=reachable(graph,near[0],c.gateX-28);if(!graph.nodes.some(n=>n.x>c.gateX-130&&n.y<480&&ret.has(n.id)))issues.push('Underground return blocked');}}}
 if(!graph.nodes.some(n=>n.x>l.goal.x&&all.has(n.id)))issues.push('Stargate unreachable');
 for(const c of l.checkpoints)if((l.worldHazards||[]).some(h=>Math.abs(h.x-c.x)<180)||l.spikes.some(h=>Math.abs(h.x-c.x)<100))issues.push('Unsafe checkpoint');
 return {world:l.id,nodes:graph.nodes.length,reachable:all.size,issues,occupancy:validatePlacements(l),mechanic:l.environmentMechanic};}
if(process.argv[1]?.endsWith('validate-routes.mjs')){const results=[];for(let i=0;i<15;i++){const r=validateRoute(makeLevel(i));results.push(r);console.log(JSON.stringify(r));}fs.writeFileSync('artifacts/v130-map-validation.json',JSON.stringify(results,null,2));if(results.some(r=>r.issues.length||r.occupancy.length))process.exitCode=1;}
